name: Concurrency
# on: push
on:
  workflow_dispatch:

# this workflow is used to test the concurrency feature of GitHub Actions
concurrency: ${{ github.workflow }}
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120