name: Conditions
# on: push
on:
  workflow_dispatch:
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        # divide the run id
        if: ${{ contains(github.run_id, '1') }}