name: Convert
# on: push
on: workflow_dispatch
env:
  TIMEOUT: 1
jobs:
  # this job is error, because sleep 120 is overing timeout 1 minute
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
        # convert from string to number
        timeout-minutes: ${{ fromJSON(env.TIMEOUT) }}