name: Fail-fast enable matrix
# on: push
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # sleep each process at a different time
        time: [10, 20, 30]
    steps:
      - run: sleep "${SLEEP_TIME}" && exit 1
        env:
          SLEEP_TIME: ${{ matrix.time }}