name: Flow control
# on: push
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: exit "$(( RANDOM % 2 ))"
      - run: exit 1
        id: error
      - run: echo "Catch error step"
        # If failure() is omitted, success() is implicitly assumed to exist.
        if: ${{ failure() && steps.error.outcome == 'failure' }}

        # ${{ steps.error.outcome == 'failure' }} 
        # is assumed to ${{ success() && steps.error.outcome == 'failure' }}