name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        # set step id, write to GITHUB_OUTPUT
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          # read from steps context
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"