name: Job summaries
# on: push
on: workflow_dispatch
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      # output Markdown text to job summary
      - run: |
          {
            echo "## Example Title :rocket:";
            echo "- first line";
            echo "- second line";
          } >> "${GITHUB_STEP_SUMMARY}"