name: Log group
# on: push
on: workflow_dispatch
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: | # start log group
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"