name: Naming
# on: push
on: 
  workflow_dispatch:
jobs:
  print:
    # select job name  
    name: Super Useful Job
    runs-on: ubuntu-latest
    steps:
      # select step name
      - name: Amazing Script
        run: echo "Hello"