name: Status check functions
# on: push
on:
  workflow_dispatch:
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
    # error because finish status is not 0
      - run: exit 1
      - run: echo "Hello"
        if: ${{ failure() }}